### ISSUE TITLE
unable to connect to server or restore my btc address

### ISSUE THREAD

**Issue by ak889** [darkwallet/darkwallet#121]
Hi. I have been unable to connect to the server for several days (in Settings when I click on the unsystem server and then on "Connect to selected server" I get the error message "error connecting.") I am running the latest stable version of Debian. It was connecting fine before and all my other programs can connect to the internet fine. I upgraded all the darkwallet files but that didn't work. I then followed the instructions on the wiki that say to delete storage and restart but that didn't help either and also created another problem because even though I entered my seed the program doesn't show my bitcoin address that I have some bitcoins in. Will this address be recovered when I am able to connect to the server? The wiki says that if I have my seed i can recover my funds. Is there an alternate server I can connect to? Thanks for your help.

**Comment by dabura667** [comment]
1. You should not be using real bitcoins with this software. You were warned.
2. The server is down, it is an alpha version of software which you were told not to use with real coins, any problems caused because servers are down (you couldn't access your coins etc. when you needed them) are your responsibility, you were warned NOT to use real coins.
3. Please check the other issues before making a new issue. #102 is an issue I created. There, one of the devs clearly states "You have to manually regenerate your addresses for now" This means that once you have restored your seed, you much recreate any extra pockets you made, and then go into each pocket and click "New Address" until all your balances are there. You must also click "New change address" to restore your change addresses as well.

However, recreating your addresses will not give you a balance right now, as the servers are down. So your dark wallet is blind to the blockchain. It can not check its own balance if it can not connect to the server.

My advice is, 1. Wait until the servers come back online. 2. Make new addresses in each pocket that you remembered using until you get all your balances back. 3. Remember that this software is in alpha and your balances might not be shown properly.

If you still can't find all your funds, then just hold on to your seed and wait until the official release when the software will properly be able to find all of your funds. As long as you have your seed, your funds will be found eventually.

I will say this again. This is an alpha build, and you were warned not to use it with real bitcoins. Once you are able to, I recommend sending all your real bitcoins OUT of dark wallet until the official release. Until then, create a testnet account and play around with the features.

**Comment by ak889** [comment]
Many thanks for this helpul information. Do you know approximately when the servers will be back online?

**Comment by dabura667** [comment]
They were back online a couple hours after you closed this.

They will be on and off until release, just keep checking.
