### ISSUE TITLE
Public key disappeared from pocket

### ISSUE THREAD

**Issue by ohboi** [darkwallet/darkwallet#163]
So I've created a pocket and sent a (mainnet) transaction to one of the addresses in it (the pocket one): http://i.imgur.com/sfWnAti.png

Balance wasn't refreshing after 1 confirmation, so I've rescanned the seed and restarted the extension.

The address disappeared altogether now. What happened and what should I do now?

**Comment by ohboi** [comment]
Update: I can sign a message using the wallet, but I don't see it in any of my pockets.

How can I access it?

**Comment by dabura667** [comment]
Try changing the filter from "Unused" to "All"

**Comment by ohboi** [comment]
Tried that, didn't work.

**Comment by dabura667** [comment]
Did you check all the pages while set to "All"? There's only 10 addresses per page.

**Comment by ohboi** [comment]
Yes, the addy is not in the list, I'm very positive about this.

**Comment by dabura667** [comment]
Did you try clicking "New Address" to see if maybe it came up?

**Comment by ohboi** [comment]
Tried for a bunch of times (in different pockets, too), did not work :(

**Comment by dabura667** [comment]
What about the client you sent the bitcoins FROM? (to darkwallet)

What does it say about the transaction?

**Comment by dabura667** [comment]
Had you ever used that pocket to receive a stealth transaction? Might you have sent your bitcoins to one of the addresses generated from a prior stealth transaction?

**Comment by ohboi** [comment]
The transaction shows up on the blockchain (10 confirmations), and no, it was sent to a normal addy, not a stealth one.

**Comment by veox** [comment]
This is indeed a bug.

@ohboi's provided me with the private data needed to debug the issue. It turns out they've sent to an address marked "pocket", which is ~~present~~ displayed immediately when creating a new pocket, but not after restarting.

I'm sure this is unintended behaviour, since "pocket addresses" are just an internal detail of [the hierarchy implementation](https://wiki.unsystem.net/en/index.php/DarkWallet/HDWallet#Tree_structure), and should probably never be displayed.

~~It would be nice, however, to provide @ohboi with a way to retrieve the funds, since it's mainnet. Perhaps make DW scan the pocket key, too?..~~

~~EDIT: never mind, I've extracted the private keys, now just waiting for @ohboi to get in touch.~~

**Comment by ohboi** [comment]
Thank you so much for your help, veox.
