### ISSUE TITLE
Mixing not working, all attempts fail.

### ISSUE THREAD

**Issue by VivaLaPanda** [darkwallet/darkwallet#192]
I've been using darkwallet for a couple weeks, and love it! However, I've enabled mixing, but none of my transactions are actually being mixed. My budget is set at about 1000(mBTC), and the target mixings are at the default 5.

**Comment by Dark2014** [comment]
Same issue here!
Also if I close the Browser and login again later, the cross in the checkbox of "enable mixing" is gone and I have to check again.

1) Latest Darkwallet version, fresh installation (tried on Win7 and Debian).
2) Fresh Chrome without any changes or plugins.

But my hole internet traffic is forced to the Tor network, could this be the problem?

**Comment by VivaLaPanda** [comment]
I'm in clearnet, so I con't see that being the issue. I'm running Windows 8.
On 11/3/2014 06:04:09, Dark2014 notifications@github.com wrote:
Same issue here!
Also if I close the Browser and login again later, the cross in the checkbox of "enable mixing" is gone and I have to check again.
1) Latest Darkwallet version, fresh installation (tried on Win7 and Debian).
2) Fresh Chrome without any changes or plugins.
But my hole internet traffic is forced to the Tor network, could this be the problem?
&mdash;

**Comment by caedesvvv** [comment]
there may be nobody listening for mixing

please try with two wallets open, one listening for mixes and the other one mixing

**Comment by caedesvvv** [comment]
(removed two messages about a bug we thought was affecting 0.6.0 but turns out it doesnt)

**Comment by VivaLaPanda** [comment]
How do you set a wallet listening? Is that just default after selecting the mixing option? Also, if that is the case, there should definitely be an option to cancel the transaction if the mixing fails, and also possible show some indicator of approximately how many listening wallets are connected.

**Comment by Dark2014** [comment]
@VivaLaPanda 
If you set the mixing option I think the listening for the pocket should be enabled.

@caedesvvv 
I tryed now with 3 wallets, it was not possible to use mixing option because if I change between the wallets the cross in the checkbox of "enable mixing" is gone. This should be fixed soon to make the option usefull.

So I set in all wallets "Enforced mixing" and I send from all wallets a amount of 0.001 BTC.
If I change between the 3 wallets I can see that any wallet shows a blue box with "mixing Announcing" and "Pending mixer transaction 33%". 

So 3 wallets listening for mixing but nothing happens!
I think if the app have no connection to the lobby-chat it has also no connection to the listening of other wallets. Both problems came from the same reason. But we tried with fresh installation and different OS, so I dont know whats wrong or what could I try to fix it.

**Comment by caedesvvv** [comment]
ok just fixed a bug breaking communications on some chrome versions (we seen the issue on regular windows installation, but we don't know what versions are affected... seems it can be widespread issue), should fix this issue as well: https://github.com/darkwallet/darkwallet/commit/90d3ebdbd593d3c6340792877184a1fb519e2e06

It was producing errors on the backend, here are instructions for getting more debugging information and see if something is broken: https://wiki.unsystem.net/en/index.php/DarkWallet/Debug

**Comment by Dark2014** [comment]
@caedesvvv 
I used the developers version now and the Trollbox problem is solved.
But CoinJoin did not work, tried with 2 wallets announcing for a 0,01BTC CoinJoin (Enforced mixing).

**Comment by caedesvvv** [comment]
note you shouldnt have two wallets announcing, it must be one listening and one announcing atm.

maybe there is more clients listening now for mixes, you can try with either 0.6.1 or develop (now getting ready for 0.7 so will require an upgrade)

**Comment by Dark2014** [comment]
@caedesvvv 
Sorry but I dont understand, what the hell is "listening"?
I dont see any feature like this in the wallet, so please tell me how to find this option.

The only option I see is the "enable mixing" for the pocket. 
BUT I cant use this feature, I already wrote about this problem two times. 

Here:  "Also if I close the Browser and login again later, the cross in the checkbox of "enable mixing" is gone and I have to check again."

And here:  "I tryed now with 3 wallets, it was not possible to use mixing option because if I change between the wallets the cross in the checkbox of "enable mixing" is gone. This should be fixed soon to make the option usefull".

**Comment by caedesvvv** [comment]
By listening I mean someone enabled "automatic mixing" for a pocket.

The pocket stops listening now when you change wallets, also to be able to mix, both need to be connected at the same time.

**Comment by Dark2014** [comment]
@caedesvvv 
Mixing worked today for me!
I changed nothing, so some change on the server-side should fix this problem.
I try 4-5 mixings today and it works fine, so hope this problem is solved now.

Ok, so for the "automatic mixing" I have to be online and logged in!
I understand now, this is because my wallet-keys are also offline if I am not logged in my wallet!?!?

**Comment by caedesvvv** [comment]
Ok, but just to clarify:

It's not server side changes, it's that there was other people listening when you sent.

And to the other question, yes if you're not logged in to your wallet you're offline and cant be mixing, you can just receive funds since that's enabled by bitcoin p2p technology

**Comment by Dark2014** [comment]
@caedesvvv 
Ah ok, if no changes on the server, than I was wrong.

I was not able to test with "automatic mixing" with the new 0.7.0, because I cant open two wallets at the same time and I thought that "Announcing" should also work the same way.
In this case the mixing problem is solved together with the Trollbox problem.

So I think you can close here!
