### ISSUE TITLE
Mixing never works

### ISSUE THREAD

**Issue by Dark2014** [darkwallet/darkwallet#194]
Hi,

I tried to use the mixing with real BTC but it never works. I enabled "Enforced Mixing" and tried it for 2-3 days with about 30 different transfers. Sometimes I let it try for a few hours, but never get any success.

For transfers without mixing I am able to receive and send Bitcoins without problems and also stealth address works fine, so this is not the problem.

1) Latest Darkwallet version, fresh installation (tried on Win7 and Debian).
2) Fresh Chrome without any changes or plugins.

But my hole internet traffic is forced to the Tor network, could this be the problem?
(I use Whonix to force the traffic: https://www.whonix.org)

**Comment by caedesvvv** [comment]
tor shouldn't be a problem.

note to mix you have to make sure there is someone at the other side to mix. enforced mixing just means it wont send without mixing. so, someone needs to have a pocket mixing, and someone else must be sending. you can put a pocket to listen but for now it wont mix with yourself like that.

maybe there is no-one mixing now? note its not really recommended to do so with real btc, usually best is ask in the lobby if someone is mixing.

closing because the task has no specific information.
