### ISSUE TITLE
"Receiving" balance does not show when restoring from seed

### ISSUE THREAD

**Issue by scottrobertson** [darkwallet/darkwallet#205]
Using latest alpha (0.7.0)

Cannot see receiving balance, or anything in history tab after restoring wallet.

Steps to reproduce:
- Create wallet
- Receive transactions
- Delete wallet (before they are confirmed)
- Restore from seed
- "History" tab is empty
- No longer see the "receiving" balance in the top bar.

---

Let me know if you need any more info to reproduce.

**Comment by caedesvvv** [comment]
You may need to run the scanner after restoring to make sure all addresses with funds are found.

Also, scanner in 0.7 is broken (just fixed it on https://github.com/darkwallet/darkwallet/commit/67ab22bebe1a8f6a2dc05c7ddf3e963378c48c37). We're looking to fix another error and then we'll make a point release fixing critical issues.

You can either update to git (not recommended unless you're experienced developer) or wait for a release.

Closing the task since the underlying error is fixed, just waiting for release.

**Comment by scottrobertson** [comment]
Awesome, thanks for the update @caedesvvv
