### ISSUE TITLE
Change doesn't get recorded after succesfull transaction

### ISSUE THREAD

**Issue by JimM2** [darkwallet/darkwallet#206]
Hello,

I had recently sent a payment to someone, but the coinjoin amount (remaining balance in wallet) was never returned to me... I had made a payment, but the remaining amount in my wallet was lost.
Thank you-

**Comment by JimM2** [comment]
Also, this is the error message that I received: 
Uncaught ReferenceError: Bitcoin is not defined

if (version > 4 && !$scope.scanParams.scanOld) {
          keyStore = identity.store.getPrivateData(password);
          rootKey = Bitcoin.HDNode.fromBase58(keyStore.privKey);
          mpks = identity.store.get('mpks');
          oldStyle = false;
      }

**Comment by caedesvvv** [comment]
The error referencd on the scanner has been fixed in https://github.com/darkwallet/darkwallet/commit/67ab22bebe1a8f6a2dc05c7ddf3e963378c48c37

Regarding the missing funds, seems the change address was not saved. Other people have had similar issues but we haven't found yet the reason, the funds are not lost though.

You can recover your funds by triggering change address generation, this can be done from code by following instructions from: https://forum.unsystem.net/t/darkwallet-hack-wallet-magically-transferred-all-my-money-to-someone-elses-stealth-address/378. Also you can apply the fix above yourself or get the git version (but note the git version can lead to other problems since it's still wip).

Leaving this issue open until we can solve the issue with change addresses not getting saved.

**Comment by JimM2** [comment]
Thank you so much!  I fixed mine by adding the missing reference in the developer file src/js/frontend/controllers/scanning.js into my Alpha 7 folder in my C:\Users\Main\Desktop\Darkwallet\darkwallet-0.7.0\js\frontend\controllers directory, replacing the old one.  After re-scanning, my lost coins were magically returned.

**Comment by caedesvvv** [comment]
Great to know it worked for you :)

(and good job backporting the fix for the scanner yourself :))

**Comment by caedesvvv** [comment]
ok, seems to be a full storage quota, we've lifted plugin restrictions for upcoming version
closing this ticket unless we can get another reason for this... but so far our investigation shows it's the quota issue.
