### ISSUE TITLE
Temporal (optionally non-temporal), short, readable lobby usernames for display

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#49]
The lobby as of now makes it hard to reply to each other, also, you can't temporally identify people because after every browser exit, the Cloak changes.

My suggestions:
- have short, two-word cloak names, like "colorful python", "plausible ornament". etc. Display this in the lobby chat feed. Then you can call people their names and tell the person you are responding to their question. Funny pixel faces can stay.
- have an option where one can decide to stick with their cloak until they deliberately press regenerate. ("Sticky cloak"?)
- when regenerating the cloak, the old cloak stays in the peer list, cluttering it. Old cloaks should disappear.

**Comment by caedesvvv** [comment]
note the lobby now is just foundation work for something where those features will be fullfilled, we will be working on that during this week so you will see.

it's not worth it to add temporary workarounds because we intend to advance this fast.

**Comment by leafcutterant** [comment]
I meant "temporary" not as the nature of the workaround, but as the permanence of the cloak, to have a switch to make it permanent during switching between wallets or exiting the browser.

What do you think about being able to specify cloack name and picture? Of course, only as opt-in.

**Comment by sembrestels** [comment]
We don't like the concept of sticky cloak because the idea is that it protects your privacy. What you call sticky cloak is the identity for us. If you pair with a contact, you send him/her your identity info. Right now it is just your name and your stealth, but we want to implement a more complex identity and relationship system. And yes, the identity system would be able to include an avatar also.

**Comment by caedesvvv** [comment]
the pair and beacon system already takes care of this in a general way.
