### ISSUE TITLE
Unbroadcasted transactions get stuck

### ISSUE THREAD

**Issue by cryptosig** [darkwallet/darkwallet#79]
Transactions that fail get stuck in the Darkwallet queue and never leave or get processed.

**Comment by millsdmb** [comment]
example of what I'm experiencing (MainNet):

![image](https://cloud.githubusercontent.com/assets/7471116/2871879/c045aa4c-d32c-11e3-9b96-b35d49b46dc4.png)

**Comment by veox** [comment]
Confirming same issue for the following scenario:

Using own gateway/broadcaster/obelisk; if broadcaster is unavailable during initial transmission to the gateway, DW will display "Broadcasting going slow" several times, then (seemingly) stop broadcasting.

Restarting chromium doesn't help: expecting DW to at least show the same "going slow" notification; instead, it still shows the same transaction in the pop-up with 0 confirmations (as above), but the tx is gone from "Latest transactions" list. Also, the wallet balace is restored, as if there is no pending transaction.

**UPDATE**: in this case, it is possible to go through the sending process again, creating the same transaction (inputs/outputs), and (with a now-running broadcaster) the tx gets sent.

`darkwallet 0.1.0-50-gff60be6`

**Comment by veox** [comment]
@cryptosig, @millsdmb - was CoinJoin used for these? It is enabled by default. Has your browser been restarted after that?

**Comment by millsdmb** [comment]
Yes coinjoin to stealth address. Browser restarted without success.

**Comment by cryptosig** [comment]
No coinjoin, from stealth address to anywhere.

**Comment by millsdmb** [comment]
![image](https://cloud.githubusercontent.com/assets/7471116/2879302/3329005e-d468-11e3-986f-e3204d846f8f.png)

**Comment by caedesvvv** [comment]
Pending transactions can now be cleared from the history tab:
Introduced in  https://github.com/darkwallet/darkwallet/commit/6f3747230efc4fe7d56b4a359024c5766a0a6ff7.

**Comment by millsdmb** [comment]
Transactions still fail to broadcast, however. Is this being resolved?

**Comment by ABISprotocol** [comment]
@caedesvvv I wanted to let you know that this is indeed, me.  However, I haven't yet updated git as per [this advisory](http://article.gmane.org/gmane.linux.kernel/1853266) and right now I'm merely logging in to githhub so that you'd see the difference from when I e-mail it with PGP signature as I normally have done in the past, compared to now, when I'm not.  Oddly, I noticed that before when I tried to send something as a PGP signed message it sent no problem -- [example here](https://forum.unsystem.net/t/interoperability-and-trans-identical-identity-decentralization-proposals-thoughts-for-review/333/22) - and when I tried to do so later on it wouldn't as you can observe from [the same thread](https://forum.unsystem.net/t/interoperability-and-trans-identical-identity-decentralization-proposals-thoughts-for-review/333/27?u=abisprotocol). 

Basically since around Nov. 29th, as you can see from the link above, I have had problems trying to PGP e-mail post reply to the forum - no problem actually doing that, but it never appears in your forum. In other words, the riseup servers were functioning, the keys were well as far as I could tell, and so forth, tbird and enigmail and even torbirdy etc. All working.  Message signed and sent.  The problem seemed to be that somewhere along the way the (PGP signed) messages never would make it to the unsystem forum at some point after Nov. 29th.  At that point (Dec. 3-6) I was in the hospital anyway and so I was kind of having a rough time concerning myself over PGP it the fact is
any expiration or modification processess I had done previously (which were [documented in unsystem](http://www.g-loaded.eu/2010/11/01/change-expiration-date-gpg-key/) if I recall correctly)  would have been the least of my concerns, I was in and out of conciousness due to the pain.  

Touch base with @willpangman or @nikosbentenitis and ask them about me ~ again, if you like. If you'd rather not that's ok too.

I finally got some records back from the doctor on my case which I can send to you, but to be quite honest I am concerned to send them to you @caedesvvv - even in redacted format.  apprently with several people there having been detained I don't know the status of some of your equipment and I think to be quite honest, developers in any region of the world who've had any equipment confiscated (for no matter how brief a time) need to be clear about it and state what keys were likely to have been compromised and republish said keys so that we don't keep trying to communicate with potentially or probably compromised devices. See for example this nonsense story [here](https://www.thespainreport.com/13349/catalan-police-take-anarchist-terror-group-barcelona-1000-supporters-march-protest/).  In some aspects I'm sure the story might have gotten some things correct but in many ways I am sure it is flawed just as you coud probably find criticism in my approach to try to contact you here.
